projekt:
    resource: "@ProjektBundle/Resources/config/routing.yml"
    prefix:   /pb

epopee:
    resource: "@EpopeeBundle/Resources/config/routing.yml"
    prefix:   /pt

hello:
    resource: "@HelloBundle/Resources/config/routing.yml"
    prefix:   /hw

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"