projekt_homepage:
    path:     /
    defaults: { _controller: ProjektBundle:Default:index }

projekt_category:
    path:     /category
    defaults: { _controller: ProjektBundle:Default:category }

projekt_subcategory:
    path:     /category/sub
    defaults: { _controller: ProjektBundle:Default:subcategory }

